version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      major:
        update-types:
          - major
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      major:
        update-types:
          - major
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
